apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::169987382509:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1N1VPZABULACJ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::169987382509:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-04T16:27:35Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1482"
  uid: c2815e2c-dcc2-474b-9761-116e23bb4ac7
